
# Name your project! Project names should contain only lowercase characters
# and underscores. 
# name or the intended use of these models
name: 'tabby_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'tabby_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  tabby_dbt:
    # Medallion architecture layers
    staging:
      +materialized: view
      +schema: staging
    
    silver:
      dimensions:
        +materialized: table
        +schema: silver
      facts:
        +materialized: table
        +schema: silver
    
    gold:
      +materialized: table
      +schema: gold
      
      customers:
        +tags: ["customers"]
      merchants:
        +tags: ["merchants"]
      transactions:
        +tags: ["transactions"]
      finance:
        +tags: ["finance"]
